/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as OccasionsRouteImport } from './routes/occasions'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GiftFinderRouteImport } from './routes/gift-finder'
import { Route as CustomOrdersRouteImport } from './routes/custom-orders'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as CareRouteImport } from './routes/care'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OccasionsIndexRouteImport } from './routes/occasions.index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as CategoryIndexRouteImport } from './routes/category.index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as OccasionsSlugRouteImport } from './routes/occasions.$slug'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsRoute = OccasionsRouteImport.update({
  id: '/occasions',
  path: '/occasions',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftFinderRoute = GiftFinderRouteImport.update({
  id: '/gift-finder',
  path: '/gift-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomOrdersRoute = CustomOrdersRouteImport.update({
  id: '/custom-orders',
  path: '/custom-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsIndexRoute = OccasionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OccasionsRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoryRoute,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsSlugRoute = OccasionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OccasionsRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoryRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care': typeof CareRoute
  '/category': typeof CategoryRouteWithChildren
  '/custom-orders': typeof CustomOrdersRoute
  '/gift-finder': typeof GiftFinderRoute
  '/journal': typeof JournalRouteWithChildren
  '/lookbook': typeof LookbookRoute
  '/occasions': typeof OccasionsRouteWithChildren
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size-guide': typeof SizeGuideRoute
  '/api/chat': typeof ApiChatRoute
  '/category/$slug': typeof CategorySlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/occasions/$slug': typeof OccasionsSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/category/': typeof CategoryIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/occasions/': typeof OccasionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care': typeof CareRoute
  '/custom-orders': typeof CustomOrdersRoute
  '/gift-finder': typeof GiftFinderRoute
  '/lookbook': typeof LookbookRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size-guide': typeof SizeGuideRoute
  '/api/chat': typeof ApiChatRoute
  '/category/$slug': typeof CategorySlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/occasions/$slug': typeof OccasionsSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/category': typeof CategoryIndexRoute
  '/journal': typeof JournalIndexRoute
  '/occasions': typeof OccasionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care': typeof CareRoute
  '/category': typeof CategoryRouteWithChildren
  '/custom-orders': typeof CustomOrdersRoute
  '/gift-finder': typeof GiftFinderRoute
  '/journal': typeof JournalRouteWithChildren
  '/lookbook': typeof LookbookRoute
  '/occasions': typeof OccasionsRouteWithChildren
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/size-guide': typeof SizeGuideRoute
  '/api/chat': typeof ApiChatRoute
  '/category/$slug': typeof CategorySlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/occasions/$slug': typeof OccasionsSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/category/': typeof CategoryIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/occasions/': typeof OccasionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/care'
    | '/category'
    | '/custom-orders'
    | '/gift-finder'
    | '/journal'
    | '/lookbook'
    | '/occasions'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/size-guide'
    | '/api/chat'
    | '/category/$slug'
    | '/journal/$slug'
    | '/occasions/$slug'
    | '/product/$handle'
    | '/category/'
    | '/journal/'
    | '/occasions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/care'
    | '/custom-orders'
    | '/gift-finder'
    | '/lookbook'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/size-guide'
    | '/api/chat'
    | '/category/$slug'
    | '/journal/$slug'
    | '/occasions/$slug'
    | '/product/$handle'
    | '/category'
    | '/journal'
    | '/occasions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/care'
    | '/category'
    | '/custom-orders'
    | '/gift-finder'
    | '/journal'
    | '/lookbook'
    | '/occasions'
    | '/shipping-returns'
    | '/shop'
    | '/sitemap.xml'
    | '/size-guide'
    | '/api/chat'
    | '/category/$slug'
    | '/journal/$slug'
    | '/occasions/$slug'
    | '/product/$handle'
    | '/category/'
    | '/journal/'
    | '/occasions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareRoute: typeof CareRoute
  CategoryRoute: typeof CategoryRouteWithChildren
  CustomOrdersRoute: typeof CustomOrdersRoute
  GiftFinderRoute: typeof GiftFinderRoute
  JournalRoute: typeof JournalRouteWithChildren
  LookbookRoute: typeof LookbookRoute
  OccasionsRoute: typeof OccasionsRouteWithChildren
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SizeGuideRoute: typeof SizeGuideRoute
  ApiChatRoute: typeof ApiChatRoute
  ProductHandleRoute: typeof ProductHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions': {
      id: '/occasions'
      path: '/occasions'
      fullPath: '/occasions'
      preLoaderRoute: typeof OccasionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-finder': {
      id: '/gift-finder'
      path: '/gift-finder'
      fullPath: '/gift-finder'
      preLoaderRoute: typeof GiftFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-orders': {
      id: '/custom-orders'
      path: '/custom-orders'
      fullPath: '/custom-orders'
      preLoaderRoute: typeof CustomOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions/': {
      id: '/occasions/'
      path: '/'
      fullPath: '/occasions/'
      preLoaderRoute: typeof OccasionsIndexRouteImport
      parentRoute: typeof OccasionsRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/category/': {
      id: '/category/'
      path: '/'
      fullPath: '/category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions/$slug': {
      id: '/occasions/$slug'
      path: '/$slug'
      fullPath: '/occasions/$slug'
      preLoaderRoute: typeof OccasionsSlugRouteImport
      parentRoute: typeof OccasionsRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CategoryRouteChildren {
  CategorySlugRoute: typeof CategorySlugRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategorySlugRoute: CategorySlugRoute,
  CategoryIndexRoute: CategoryIndexRoute,
}

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren,
)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface OccasionsRouteChildren {
  OccasionsSlugRoute: typeof OccasionsSlugRoute
  OccasionsIndexRoute: typeof OccasionsIndexRoute
}

const OccasionsRouteChildren: OccasionsRouteChildren = {
  OccasionsSlugRoute: OccasionsSlugRoute,
  OccasionsIndexRoute: OccasionsIndexRoute,
}

const OccasionsRouteWithChildren = OccasionsRoute._addFileChildren(
  OccasionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareRoute: CareRoute,
  CategoryRoute: CategoryRouteWithChildren,
  CustomOrdersRoute: CustomOrdersRoute,
  GiftFinderRoute: GiftFinderRoute,
  JournalRoute: JournalRouteWithChildren,
  LookbookRoute: LookbookRoute,
  OccasionsRoute: OccasionsRouteWithChildren,
  ShippingReturnsRoute: ShippingReturnsRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SizeGuideRoute: SizeGuideRoute,
  ApiChatRoute: ApiChatRoute,
  ProductHandleRoute: ProductHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
